name: Upload test artifacts

description: Upload various artifacts produced by our testing process

inputs:
  use-gha:
    description: If set to any value, upload GHA. Otherwise upload to S3.
    required: false
  file-suffix:
    description: Suffix to add to the filename of the artifacts
    required: true
  gh-token:
    description: GITHUB_TOKEN secret
    required: true

runs:
  using: composite
  steps:
    - name: Get workflow job ID
      id: get-job-id
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.gh-token }}
      run: |
        set -x
        python3 -m pip install requests==2.26.0
        GHA_WORKFLOW_JOB_ID=$(python3 .github/scripts/get_workflow_job_id.py "${GITHUB_RUN_ID}" "${RUNNER_NAME}")
        echo "::set-output name=job-id::${GHA_WORKFLOW_JOB_ID}"

    # Mac/Linux zip
    - name: Zip JSONs for upload
      if: runner.os != 'Windows'
      shell: bash
      env:
        FILE_SUFFIX: ${{ inputs.file-suffix }}_${{ steps.get-job-id.outputs.job-id }}
      run: |
        # Remove any previous test jsons if they exist
        rm -f test-jsons-*.zip
        zip -r "test-jsons-${FILE_SUFFIX}.zip" test -i '*.json'

    - name: Zip test reports for upload
      if: runner.os != 'Windows'
      shell: bash
      env:
        FILE_SUFFIX: ${{ inputs.file-suffix }}_${{ steps.get-job-id.outputs.job-id }}
      run: |
        # Remove any previous test reports if they exist
        rm -f test-reports-*.zip
        zip -r "test-reports-${FILE_SUFFIX}.zip" test -i '*.xml'

    # Windows zip
    - name: Zip JSONs for upload
      if: runner.os == 'Windows'
      shell: powershell
      env:
        FILE_SUFFIX: ${{ inputs.file-suffix }}_${{ steps.get-job-id.outputs.job-id }}
      run: |
        # -ir => recursive include all files in pattern
        7z a "test-jsons-$Env:FILE_SUFFIX.zip" -ir'!test\*.json'

    - name: Zip test reports for upload
      if: runner.os == 'Windows'
      shell: powershell
      env:
        FILE_SUFFIX: ${{ inputs.file-suffix }}_${{ steps.get-job-id.outputs.job-id }}
      run: |
        # -ir => recursive include all files in pattern
        7z a "test-reports-$Env:FILE_SUFFIX.zip" -ir'!test\*.xml'

    # S3 upload
    - name: Store Test Downloaded JSONs on S3
      uses: seemethere/upload-artifact-s3@v3
      if: ${{ !inputs.use-gha }}
      with:
        retention-days: 14
        if-no-files-found: warn
        path: test-jsons-*.zip

    - name: Store Test Reports on S3
      uses: seemethere/upload-artifact-s3@v3
      if: ${{ !inputs.use-gha }}
      with:
        retention-days: 14
        if-no-files-found: error
        path: test-reports-*.zip

    # GHA upload
    - name: Store Test Downloaded JSONs on Github
      uses: actions/upload-artifact@v2
      if: inputs.use-gha
      with:
        retention-days: 14
        if-no-files-found: warn
        path: test-jsons-*.zip

    - name: Store Test Reports on Github
      uses: actions/upload-artifact@v2
      if: inputs.use-gha
      with:
        name: test-reports-${{ inputs.file-suffix }}_${{ steps.get-job-id.outputs.job-id }}.zip
        retention-days: 14
        if-no-files-found: error
        path: test-reports-*.zip
